#!/usr/bin/env bash
set -euo pipefail

SCAN_RESULTS_FILE="${1:-promptfoo-code-scan.json}"
NOTE_JSON_FILE="${2:-merge-request-note.json}"
MAX_FINDINGS="${MAX_FINDINGS:-20}"

if [[ ! -f "$SCAN_RESULTS_FILE" ]]; then
  echo "Scan results file not found: $SCAN_RESULTS_FILE" >&2
  exit 2
fi

if ! command -v jq >/dev/null 2>&1; then
  echo "jq is required" >&2
  exit 2
fi

COMMENT_BODY=$(jq -r --argjson max_findings "$MAX_FINDINGS" '
  def loc(c):
    if c.file then
      "`" + c.file + (if c.line then ":" + (c.line|tostring) else "" end) + "` - "
    else
      ""
    end;
  def sev(c):
    if c.severity then "**" + (c.severity | ascii_upcase) + "** - " else "" end;
  [
    "## Promptfoo Code Scan",
    "",
    (.review // "Scan complete."),
    "",
    "### Findings",
    (
      if ((.comments // []) | length) == 0 then
        "- No findings"
      else
        ((.comments // [])[0:$max_findings] | map(
          "- " + sev(.) + loc(.) + (.finding // "Finding omitted")
          + (if .fix then "\n  - Suggested fix: " + .fix else "" end)
        ) | .[])
      end
    ),
    "",
    "_Generated by Promptfoo in IBM Cloud Continuous Delivery._"
  ] | join("\n")
' "$SCAN_RESULTS_FILE")

jq -n --arg body "$COMMENT_BODY" '{body: $body}' > "$NOTE_JSON_FILE"
echo "Wrote GRIT merge request note payload to $NOTE_JSON_FILE"
